### ISSUE TITLE
(node:8300) UnhandledPromiseRejectionWarning: TypeError: twdown(...) is not a function

### ISSUE THREAD

**Issue by boypanjaitan16** [Kikobeats/twdown#1]
Hey I got this error message, how can I fix it ?

`(node:8300) UnhandledPromiseRejectionWarning: TypeError: twdown(...) is not a function
    at /Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:42:15
    at app.get (/Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:59:11)
    at Layer.handle [as handle_request] (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/layer.js:95:5)
    at /Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:275:10)
    at app.use (/Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:21:5)
(node:8300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8300) UnhandledPromiseRejectionWarning: TypeError: twdown(...) is not a function
    at /Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:42:15
    at app.get (/Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:59:11)
    at Layer.handle [as handle_request] (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/layer.js:95:5)
    at /Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:275:10)
    at app.use (/Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:21:5)
(node:8300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8300) UnhandledPromiseRejectionWarning: TypeError: twdown(...) is not a function
    at /Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:42:15
    at app.get (/Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:59:11)
    at Layer.handle [as handle_request] (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/layer.js:95:5)
    at /Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/boypanjaitan/Desktop/serverless/mdl/node_modules/express/lib/router/index.js:275:10)
    at app.use (/Users/boypanjaitan/Desktop/serverless/mdl/app.local.js:21:5)
(node:8300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)`

**Comment by boypanjaitan16** [comment]
I already install twdown using 
`$ npm install twdown --save`

and browserless
`$ npm install puppeteer browserless --save`

**Comment by boypanjaitan16** [comment]
But it's still error somehow

**Comment by Kikobeats** [comment]
I'm not actively maintaining this repo; use api.microlink.io instead 🙂
